apiVersion: operators.coreos.com/v1alpha1
kind: Namespace
metadata:
  labels:
    app: openshift-logging
    app.kubernetes.io/instance: openshift-logging
  name: openshift-gitops
  namespace: openshift-gitops