apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
    name: cluster-a
    namespace: openshift-gitops
  path: patch-overlay.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
    name: cluster-b
    namespace: openshift-gitops
  path: patch-overlay.yaml
