apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-a
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/shin-san/ocp-gitops.git
      revision: HEAD
      directories:
      - path: a/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: cluster-base
      syncPolicy:
        automated: {}
      source:
        repoURL: replace-url-here
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: integreatly.org
        kind: GrafanaDataSource
        jsonPointers:
        - /spec/datasources/0/secureJsonData/httpHeaderValue1